baseURL = "https://go.ondralinek.cz/"
languageCode = "cs-CZ"
title = "Jazyk #Go(lang)"
theme = "hugo-code-editor-theme"
disqusShortname = "ondralinek-cz"


[params]
    author = "Ondřej Linek"
    locale = "cs-CZ"
